.all-contributorsrc
README.md
other/ROADMAP.md
src/index.js
src/index.test.js

This allows you to pass in keypaths instead of just single keys.
Makes things such as {keys: ['name.first']} possible.
closes #1

feat(nested keys): add ability to pass in keypath for object value

---

README.md
src/index.js
src/index.test.js

With this commit you can now specify an array of items to rank and those items will be checked individually (before, they were joined with a comma via toString, which is sub optimal).
@conorhastings, I need this for what I'm working on right now, so if you could review this really quick that'd be awesome. If you don't have time no worries. I'll probably not need it for an hour. If you don't get to it I'll just merge it myself :)

feat(items): add support for arrays

---

README.md
package.json
src/index.js
src/index.test.js

It's reasonable to consider this change breaking, but I think that it's unlikely that anyone is depending on what I would consider a bug.
This adds our first dependency. Everything seems to be working with bundledDependencies (tested locally) and the UMD builds.
This should be merged after #9 is merged. I think I may need to rebase this branch when #9 is merged because we're doing squash-and-merge. We'll see what happens.
Closes #8

feat(match): ignore diacritics when matching by default

---

dist-test/index.js
package-scripts.js
package.json
rollup.config.js
src/index.js
src/index.test.js

Rollup is not capable of exposing a default export AND a named export as a UMD module in a useful way for the global context. So this adds some custom UMD logic to the bottom of the main file. This should hopefully never need to be touched, but there are tests that validate the CJS and ES6 module exports.
Things will be challenging when people want to use native ES6 modules with this module (because now we're not exposing this as a native ES6 module). But we weren't really doing that in the first place (we were transpiling) so that's fine for now.
Fixes #14
@rogeliog and @conorhastings, could you give this a look? Honestly, I'm pretty sure that webpack isn't really capable of doing this (without some extra work) either. So I think this manual UMD stuff is the best we can do.
[Here's an …

fix(umd): do umd manually

---

src/index.js

Previously, `keyIndex` was getting updated before min and max ranking were checked, so it could change even if the ranking itself didn't, which meant that an item could get unnecessarily demoted.

fix(sorting): change keyIndex only when ranking changes

---

src/__tests__/index.js
src/index.js

**What**:
when the search term is empty, then skipping all operations and returning the original input
**Why**:
since the matchSorter perform `sort`, it changes the input even when nothing is searched. This skip step now prevents that from happening.
**How**:
**Checklist**:

skip search/sort when search term is empty

---

src/index.js

Closes #44 
**What**:
Replaced a use of `String.prototype.includes` with `String.prototype.indexOf`. 
**Why**:
The method mentioned above is not supported by Internet Explorer, causing the lib to err when the user hasn't added a polyfill on the application side.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes#Browser_compatibility
**How**:
**Checklist**:

Replaced String.includes() with indexOf() due to IE incompatibility

---

.all-contributorsrc
README.md
src/__tests__/index.js
src/index.js

**What**:
Add the ability to set a threshold per key
**Why**:
To be able to set specific keys to only match when they meet a specified threshold
**How**:
By adding returning the keys threshold with each match and verifying that the the match is `>=` the threshold specified on its key.
**Checklist**:

Add ability to set a threshold per key

---

src/__tests__/index.js
src/index.js

**What**:
1. Sort same ranked items alphabetically rather than by the index they were inputted.
2. Updated tests.
3. One new test.
**Why**:
Currently, if items are the same rank with the same key based index, the items are sorted based on their index in the starting input. This is fine in general but I believe it makes more sense to sort them alphabetically when they have the same ranking and also by length allowing the smaller words to float to the top and make filtering a progressive act.
Example:
search: `'ap'`
input: `['wrapped','snap', 'pap']`
old output: `['wrapped','snap', 'pap']`
new output: `['pap', 'snap', 'wrapped']`
**How**:
We can take advantage of the base [String.prototype.localeCompare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Strin …

Sort same ranked items alphabetically

---

src/index.js

Bug fix. For more information: [#64](https://github.com/kentcdodds/match-sorter/issues/65)

fix: rankedItem casting to string (#64)

---

src/__tests__/index.js
src/index.js

**What**:
When using multiple keys to filter objects, the objects are always sorted by the last key in the list (if the ranks are otherwise equal), no matter which key actually matched. This PR fixes that behavior.
**Why**:
Sorting by last key is unexpected and most probably unintended py the original PR.
**How**:
I set the key to be sorted on to the one that actually matched.
**Checklist**:

fix: sort objects by matched key only (fixes #78)

---

.all-contributorsrc
src/__tests__/index.js
src/index.js

fix #100
**What**: Sort when search value is absent.
**Why**: Consistency.
**How**: Don't early escape if search value is absent.
**Checklist**:

fix: still sort when search value is absent

---

src/index.ts

**What**: Fix Type Error
**Why**: Please see issue for a description of this pull request. => #116 
**How**: When providing keys to the options object the expected type is string. Working with nested arrays in objects does however require mapping over the nested array to produce the strings that should be matched. This fixes a TypeError that expected all the keys to be of type string, by creating a Union Type with type Array<string>.
**Checklist**:

fix: :bug: TypeError

---

README.md
src/__tests__/index.ts
src/index.ts

**What**: Handle nested arrays with one or more wildcard keys. As an example
```javascript
const nestedObjList = [
{aliases: [{name: {first: 'Janice'}},{name: {first: 'Jen'}}]},
{aliases: [{name: {first: 'Fred'}},{name: {first: 'Frederic'}}]},
{aliases: [{name: {first: 'George'}},{name: {first: 'Georgie'}}]},
]
matchSorter(nestedObjList, 'jen', {keys: ['aliases.*.name.first']})
// [{aliases: [{name: {first: 'Janice'}},{name: {first: 'Jen'}}]}]
matchSorter(nestedObjList, 'jen', {keys: ['aliases.name.first']})
// [{aliases: [{name: {first: 'Janice'}},{name: {first: 'Jen'}}]}]
matchSorter(nestedObjList, 'jen', {keys: ['aliases.0.name.first']})
// []
```
**Why**: Arrays like the above are relatively common in some applications that I'm working on. I really like the intuitive sorting of …

feat: handle nested arrays with wildcard keys

---

src/index.ts

**What**: Restrict threshold/ranking type to known values (`rankings`)
**Why**: To encourage users to use predefined `rankings`
**How**: `Ranking` type was extracted from `rankings` enum
**Checklist**:

feat: restrict threshold/ranking type to known values

---

README.md
src/__tests__/index.ts
src/index.ts

Adds the ability to fully-control sorting

feat: support custom sorter

---

src/index.ts

**What**:
The `items` parameter of `matchSorter` as well as the `keys` option are being changed to `ReadonlyArray` from a plain `Array`. This more closely represents the contract of the function, as it does not modify these arrays.
Fixes #128.
**Why**:
Even though `matchSorter` does not modify its input array, it cannot be called with a value of type `ReadonlyArray`:
```typescript
const input: readonly string[] = ['foo', 'bar', 'baz'];
matchSorter(input, 'f'); // does not compile
```
**How**:
The required changes are simple: The input types are changed to `ReadyonlyArray`. This is not a breaking change, as `Array` is a subtype of `ReadonlyArray` in typescript, so "normal arrays" can be passed in like before.
**Checklist**:

Allow readonly arrays as inputs

---

README.md

**What**: Documentation for threshold was updated to remove parameters that don't exist anymore.
**Why**: These parameters don't exist anymore and the docs for the threshold are a little confusing.
**How**: Parameters removed from documentation.
**Checklist**:
- [ X ] Documentation
- [ X ] Ready to be merged
I was reading through the documentation for this on npm and was confused by what the `STRING_CASE` and `STRING_CASE_ACRONYM` values for threshold were. I checked [the code](https://github.com/kentcdodds/match-sorter/blob/main/src/index.ts#L59) and they weren't in there. I searched the repo and they only show up in the README and in a very old PR. It looks like they used to be used a long time ago but at some point got removed.

Removed obsolete threshold values

---

package.json

**What**:
Upgraded `remove-accents` from `0.4.2` to `0.5.0`
**Why**:
The upgraded version of `remove-accents` handles more cases of diacritics. For example, with the phrase "tổ chức", version `0.4.2` would remove the diacritics to be `tổ chuc`, which is incorrect. Version `0.5.0` solves this problem correctly, to `to chuc`.
**How**:
Just changed the version of `remove-accents` in `package.json`
**Checklist**:

Upgrade remove-accents to 0.5.0

---

.github/workflows/validate.yml
package.json
src/__tests__/index.ts
src/index.ts
tsconfig.json

- fix: Defer the assignment of matchSorter.rankings (fixes #147)
- chore: update deps -- blocked by <https://github.com/kentcdodds/kcd-scripts/pull/239>

fix: Defer the assignment of matchSorter.rankings

---

package.json
src/index.ts

Keeping support for older browsers by reverting the change to `Object.hasOwn` and disabling the eslint rule for the project.
Fixes: https://github.com/kentcdodds/match-sorter/issues/150
**What**: Revert back to using `Object.hasOwnProperty` instead of `Object.hasOwn`
**Why**: `Object.hasOwn` is still unsupported by some older legacy browsers that were supported before this change.
**How**: Reverted back the two changed lines and disabled the `prefer-object-has-own` in the eslint config (could also do this line-by-line, but this prevents it from accidentally being re-introduced in the project).
**Checklist**:

Prefer `Object.hasOwnProperty` for additional browser support

---

src/__tests__/index.ts
src/index.ts

**What**: Increases tolerance for typos in data and/or query text
**Why**: match sorter currently finds data with some typos, but others. E.g. "canceled" would find "cancelled", but not "cacneled".
**How**: `getClosenessRanking` calculator allows skipping one of the characters from the query. This allows finding data that contains the most common typos: swapped letters, missing letters and diverging spelling (localisation/localization). Matches that have missing letters have reduced ranking.
**Checklist**:
Since this change only affects searches where no good match (like full word, or exact start or word) gets found, I think there's no need to have add to options some flag to disable/enable this feature. If searching `ua` and finding `United States of America` is good enough right now, …

feat: support finding data with typos

---

src/__tests__/index.ts
src/index.ts

This reverts commit 8fc0645af4b2dfdbb53dd9c1c088ab52cd997f5f.
**What**:
Reverting the fuzzy matching changes from the 6.4.0 / 7.0.0 releases. ( https://github.com/kentcdodds/match-sorter/pull/153#issuecomment-2454550628 )
**Why**:
Results are... too fuzzy. Greater configurability is needed before rolling out.
**How**:
git revert 8fc0645af4b2dfdbb53dd9c1c088ab52cd997f5f
**Checklist**:

Revert "feat: support finding data with typos (#153)"

---

src/__tests__/index.ts
src/index.ts

**What**:
Fixes #159, so WORD STARTS WITH matches are returned correctly even if there is an earlier prefix that isn't at the start of a word.
**How**:
Added a new generator to call indexOf multiple times (to avoid needing to iterate through the whole string). I'm open to suggestion that this might be over-complicating it (as opposed ```if (testString.includes(` ${stringToRank}`))```) but it at least keeps the search consistent.
**Checklist**:

fix: Make sure that later matches at the start of words rank higher than earlier substring matches
