README.md

This provides an example for using this module with nested keys
closes #3

docs(readme): add documention for nested key match

---

.all-contributorsrc
README.md

Update the options section of the README by splitting code example into
multiple sections. #12

docs: Update README to show a more organized documentation.

---

.babelrc
package-scripts.js
package.json
src/index.test.js

Amazing how simpler this suddenly became.

test(jest): swap AVA for jest

---

package.json

1. Husky supports git UIs
2. Config is simpler
3. People excluding myself are maintaining it 😀

chore(githooks): swap ghooks for husky

---

.all-contributorsrc
README.md
src/index.js
src/index.test.js

Hey @kentcdodds, first of all, thanks for this great library, only stumbled upon it a few days ago but already it's truly been a godsend when implementing in-memory search/filtering functionality 😄 
One lacking feature so far however has been support for callback properties. This is especially useful for  interfacing with libraries such as Immutable.js
I've updated the tests and documentation, take a look when you get the chance and let me know if there are any changes you'd like to be made :)
Cheers!

Added support for callback properties (#21)

---

README.md
src/index.js
src/index.test.js

Finally got around to implementing this. This PR adds a new threshold called CASE_SENSITIVE_EQUAL which trumps all other matches, as discussed in #20.
I've also added a few tests and updated the README accordingly. 
Let me know if you have any feedback or would like me to make any changes :)

Add CASE_SENSITIVE_EQUAL threshold

---

.all-contributorsrc
README.md
src/index.js
src/index.test.js

This change adds support for limiting specific keys to a minimum or maximum ranking. #24

feat(ranking): Add min/max ranking options

---

src/__tests__/index.js
src/index.js

**What**: 
**Why**: https://github.com/kentcdodds/match-sorter/issues/31
**How**:
**Checklist**:

null check in nested key resolution

---

README.md

**What**: This fixes a small missing underscore in the README
**Why**: -
**How**: -
**Checklist**:

Fix readme missing underscore

---

.gitignore
README.md

**What**:
- Updating docs for nested objects with arrays scenario on how to write the `keys` for the `matchSorter` function. 
- adding `npm-debug.log` to gitignore
**Why**:
with reference to #35 
**Checklist**:

update docs and add npm-debug.log to gitignore

---

other/ROADMAP.md

I think that it would be really nice to have the possibility to get highlights for matched items.
With them we can explain sorting intuitively to end-user e.g.: using bold chars, etc.

Proposal to add highlights to roadmap

---

README.md

**What**: removing code-sponsor link from Readme as that link leads to a 404.
**Why**: I guess, code-sponsor is not support on github anymore
**How**:
**Checklist**:

remove code sponsor link from Readme

---

src/index.js

**What**: JSDoc type fix for the get highest ranking method
**Why**: JSDoc types aren't up to date
**How**: Added the correct types in the JSDoc comments
**Checklist**:

Fix jsdoc for highest ranking method

---

package.json
src/__tests__/index.js
src/index.js

For #57 
**What**:
replace Diactric.js with [remove-accents](https://github.com/tyxla/remove-accents)
**Why**:
Diactric.js is not updated for 4 years and contains a bug for cyrillic
**Checklist**:

replace Diactric.js with remove-accents

---

src/__tests__/index.js
src/index.js

**What**:
Added test case for acronym threshold.
**Why**:
Currently, the base simple match threshold is meeting the standard of the acronym threshold in certain instances.
**How**:
**Checklist**:

Don't allow simple match to meet acronym threshold

---

.prettierrc

**What**:
I added a config file for prettier.
**Why**:
To keep auto-formatting in VSCode and others consistent for all users, 
**How**:
**Checklist**:

Added prettierrc config

---

README.md

In order to demonstrate nested structure
**What**: Updating confusing docs
**Why**: Because it's not explicit enough for other use cases
**How**: Just docs
**Checklist**:
- [x ] Documentation

More explicit example

---

README.md
src/__tests__/index.js
src/index.js

**What**: Added a baseSort configuration option
**Why**: Ability to override the default stable sort for tie-breaker items
**How**: By adding a new configuration option and implementing some inversion of control and a new default
**Checklist**:

feat: add baseSort configuration option

---

README.md

Example of filtering multi-column data (tables) by splitting search term and chaining match-sorter calls.
Request to add issue discussion to documentation in #97 
README.md updates
**Checklist**:

Update README.md with multi-instance filtering

---

README.md

**What**: There was just a little typo in the README
**Why**:
**How**:
**Checklist**:

style: add missing matchSorter

---

src/index.ts

**What**: I'm removing type arguments passed explicitly to well-typed functions
**Why**: TS can infer the returned types when generics are used correctly. Passing types variables in runtime code should be used sparingly. TS contextual type checking will do its job.
**How**: I identified the places where types were passed explicitly and removed them. tested with the TS server and made sure type inference is working correclty.
**Checklist**:

Cleaning up some of the type paremeters so TS can type infer them

---

README.md

Fix a typo in the function name

---

README.md

**What**: Updated the outdated badge
**Why**: N/A
**How**: N/A
**Checklist**: N/A

fix: update github actions badge
